### ISSUE TITLE
Some Applications Do Not Register Keys Such as Enter, Space, Backspace and other.

### ISSUE THREAD

**Issue by nurudinimsirovic** [Eugeny/terminus#1003]
![image](https://user-images.githubusercontent.com/25286768/58848765-00497880-8688-11e9-9d66-223d45aa966c.png)

Using command-line utilities like NANO, VIM and some other integrated commands that come with CMD, Powershell and WSL.

The keys simply do not get registered by the application.
If they do then the cursor might end up in a weird position, sometimes even disappearing completely which is quite frustrating.. but whats even more frustrating is when I type something the cursor just gets stuck and doesn't wanna move until I start a new instance of the terminal window.

I think this is definitely some problem with the Electron app interface to a command-line app thingy that doesn't allow it to behave as expected.

**Comment by IgnusG** [comment]
Which version are you running? What’s your os release version? 
If you notice this bug, can you go to settings and open the developer console and paste its output here?

**Comment by theNurky** [comment]
OS: Microsoft Windows | Version: 10.0.18343.1

The bug appears to be present when trying to register keys that invoke newline.
Though this does not only occur with those keys, but the issue appears to be only there with some command line utilities and not all of them.

The application I'm trying to use is NANO, the Windows release can be downloaded from here: http://mediafire.com/file/dew75bb49vw7hwt

Could you forward me on how to open the developer console because F12 does not work and I couldn't see the Developer Console option anywhere inside the Settings.

Thank you

**Comment by IgnusG** [comment]
No problem, you can find the console in Settings -> Application -> Open Dev Tools Button

![image](https://user-images.githubusercontent.com/6438760/59060788-2a768280-88a2-11e9-93f0-5de5b15287f7.png)

**Comment by nurudinimsirovic** [comment]
![image](https://user-images.githubusercontent.com/25286768/59076670-8e676e00-88d7-11e9-9c79-eabbc8eb98fe.png)

**Comment by IgnusG** [comment]
Do you have ConPTY enabled? See Settings -> Shell -> Use ConPTY (on or off)

**Comment by nurudinimsirovic** [comment]
I tried both options. With ConPTY disabled the cursor does not appear to move but the problem is still the same.

The cursor only appears at the current spot if I start to press other keys than the enter, space and backspace. If I hit enter, space or backspace the cursor does not move.
