### ISSUE TITLE
Terminus breaks if it's open, on right click open with option.

### ISSUE THREAD

**Issue by ruslanguns** [Eugeny/terminus#1076]
I'd like to submit this bug, it happens on Windows when there's is an open session of Terminus and you try to open with (right click options) a new session.
It doesn't happen when you open with right click when there's no session.

![2019-06-16_14-23-50](https://user-images.githubusercontent.com/19806968/59564754-87acc980-9042-11e9-96b0-85ae6af659c0.gif)

**Comment by n1kk** [comment]
I have same issue.

**Comment by ZaLiTHkA** [comment]
I just tried to log this same issue for Terminus 1.0.82, GitHub threw out a HTTP 500 error..

however, I did discover something else beyond what this issue describes: if you use the context menu again after it closes, Terminus *does* indeed open again, along with an extra tab for the folder from which the context menu action was initiated.

also note that this behaviour of closing the app if it's already running also happens when using the Start Menu or Desktop shortcuts, so it's not limited to only the context menu route.

**Comment by ruslanguns** [comment]
@Eugeny  thanks !!

**Comment by ruslanguns** [comment]
Confirmed... This issue is fixed with release [Release: v1.0.83](https://github.com/Eugeny/terminus/releases/tag/v1.0.83)
