### ISSUE TITLE
iterm2-style inline image support

### ISSUE THREAD

**Issue by taxilian** [Eugeny/terminus#1327]
Hi,

I'd *really* like to have inline image support similar to how iterm2 works; you can find docs and examples of what I'm talking about here:

https://www.iterm2.com/documentation-images.html

I'm happy to do the work but am having trouble figuring out where to start; my thought is that I can probably tie into the xterm stuff like the clickable-links plugin does but while I've spent a little time looking over the source I'm just not sure what exactly I'm looking for.

Basically what the plugin would need to do is detect in the terminal the following syntax:

    ESC ] 1337 ; File = [optional arguments] : base-64 encoded file contents ^G

(this is extending the ansi escape codes). To fully support the spec it would support both inline (for images, etc) or not inline (click to download) types, but it seems likely this wouldn't be all that hard. We've found this useful in a number of cases but many of our employees don't have macs, so can't use it.

Thoughts?

**Comment by IgnusG** [comment]
This is dependent on the underlying render engine (xterm, hterm). They expose an API (https://github.com/Eugeny/terminus-clickable-links/blob/master/src/decorator.ts#L19) to highlight the appropriate links. 

There is an [open issue](https://github.com/xtermjs/xterm.js/issues/614) over at xterm which suggests adding support for inline images.

**Comment by taxilian** [comment]
Ahh, interesting... so it might be harder than hoped to support :-/

I will definitely look into that when I have a few minutes. It would be really slick to have that support.

**Comment by jerch** [comment]
@taxilian For xterm.js image support is on the agenda but needs more things to be covered first. Esp. a formal specification is needed as discussed here https://gitlab.freedesktop.org/terminal-wg/specifications/issues/12 If you read through the thread you'll find several technical issues with images in terminals that need to be solved first (mainly due to pixels vs. grid cells).

I have created an early stub for image support (https://github.com/jerch/xterm-addon-sixel), but we  prolly wont see offical image support in xterm.js until we have solved the technical obstacles.
