### ISSUE TITLE
Add chrome-like pinned tabs for pinned commands

### ISSUE THREAD

**Issue by RezRazi** [Eugeny/terminus#136]
I'd like to suggest a feature that would be nice to have.
Most of us usually keep using a certain set of commands over and over, like ssh to remote servers and other things. Aliases are nice, but you know what would be cool ? Being able to pin some commands to the tab bar, something chrome flavored.
![screenshot 144edit](https://user-images.githubusercontent.com/2086576/28389212-1633962a-6ccd-11e7-9006-ed6e874503dd.png)

**Comment by Eugeny** [comment]
This is probably going to be very unintuitive, since the command will be auto-started when the user clicks a tab, or will have to be started manually (which means the user sees some kind of button instead of the terminal at first). 
I'd rather implement it as a toolbar button with a favorite command list.

**Comment by Eugeny** [comment]
Posted as #137
