### ISSUE TITLE
Doesn't work in Solus OS

### ISSUE THREAD

**Issue by V3XATI0N** [Eugeny/terminus#14]
Solus OS is a Linux distribution, and the Terminus binary does start, but it's useless. User is unable to select a theme (the dropdown is empty) and no login shell is detected. Also unable to select a login shell as that dropdown is also empty. If you try to open a terminal tab, you are presented with nothing but a cursor, can't type anything, and from that point on you can't close that tab or any other, and the Settings tab also blanks out and you have to force-quit the application.

**Comment by Shackelford-Arden** [comment]
Also tried this on Solus OS (installed Dec 2017). For some reason, even modifying the config.yaml doesn't do anything in selecting a shell. My assumption is that until a shell is able to be selected, we're not able to open a new tab to a terminal.

Really bummed. I've been using Terminus for a while but with my switch over to Solus OS... Guess I'll only be able to use this if I'm not running Solus for now.

I seem unable to find any log files for some reason. Not sure where they're being put otherwise I'd see about posting something.

**Comment by tmgast** [comment]
In case this is still of interest:
I opened the dev tools and found that it was erring out attempting to read `/etc/shells`.

The easiest solution would be to symlink it, though this may not be the most correct:
`sudo ln -s /usr/share/defaults/etc/shells /etc/shells`
