### ISSUE TITLE
[Windows 10] Inconsistent hotkey behaviour with keyboard layout Dvorak

### ISSUE THREAD

**Issue by cloudbopper** [Eugeny/terminus#1416]
Hotkeys behave inconsistently with keyboard layout Dvorak on Windows 10.
With the keyboard layout set as Dvorak, typing in the terminal is in Dvorak (as expected), but some hotkeys respond according to Qwerty only (e.g. new tab, zoom in/out, find) while some respond to both Qwerty and Dvorak (e.g. copy). While configuring hotkeys in settings, the entered letters correspond to Qwerty (e.g. typing Ctrl + Shift + T in Dvorak results in the hotkey being saved as Ctrl + Shift + K, since the Dvorak letter T is co-located with the Qwerty letter K).

**Comment by JeffReeves** [comment]
I'm also experiencing this issue using the Dvorak layout on Windows 10. 

It seems to be just a visual glitch, because the hotkeys still work as expected. It's possible the input value that's being picked up by Terminus is the keycode from the keypress, and not the translated letter from the OS. 

I typically change my hotkeys in any terminal emulator to have normal `Ctrl+C/V` (copy/paste) behavior expected on Windows, and press `Ctrl+Shift+C` for the usual `Ctrl+C` (SIGINT) behavior on emacs/linux terminals. If I try to change my copy to` Ctrl+C` it shows "`Ctrl-I`", and if I try to change my paste to `Ctrl+V` it shows "`Ctrl-,`".

At first I noticed a strange behaviour, where `Ctrl+J` (where QWERTY `Ctrl+C` is) would send the SIGINT and copy highlighted text, but then I saw that there is another hotkey option in settings for "**Intelligent Ctrl-C (copy/abort)**". So I set that hotkey to `Ctrl+C` (showing as "`Ctrl-I`"), and now the behavior I want works as expected.
