### ISSUE TITLE
Unable to download release files in China

### ISSUE THREAD

**Issue by ZehuanZhang** [Eugeny/terminus#1442]
Could offer a mirror or an alternative download link in the future?

**Comment by PMExtra** [comment]
Please set a proxy rule to forward `*.s3.amazonaws.com` through a proxy. Because github used Amazon S3 storage service that be blocked sometimes in China.

On the other hand, there is also a good request for mirror settings. But I think Terminus organization could not provide any mirror server. So you should ask some public welfare organization first. If someone can provide mirror service, then Terminus will consider to provide mirror settings.

**Comment by PMExtra** [comment]
About the mirroring

First, it should fetch the `https://api.github.com/repos/eugeny/terminus/releases/latest` periodically. Then, if the above response has changed, it should fetch and cache each of `assets[].browser_download_url`. After that, replace all `browser_download_url` with the new url of mirror and save the response for the upcoming requests.

**Comment by Eugeny** [comment]
Do you guys have access to Bintray? If so, you can download releases from https://bintray.com/beta/#/eugeny/generic/terminus?tab=overview

**Comment by PMExtra** [comment]
Bintray is also a choice, but it's also blocked sometimes in China.

**Comment by PMExtra** [comment]
The ultimate solution is proxy :)
