### ISSUE TITLE
Terminus hijacks keyboard input

### ISSUE THREAD

**Issue by franciskim** [Eugeny/terminus#1509]
I'm on the latest MacOS - 10.14.6

I have CTRL + Space mapped to a system hotkey which is changing the input method.

When Terminus is running this action does not do anything - it seems to be hijacking the keyboard input even when it is not in focus.

**Comment by Eugeny** [comment]
You can disable the default assignment under Settings > Hotkeys > Toggle window

**Comment by rujorgensen** [comment]
Fixed it for me 👌.

I do think the `Hotkeys` part of the application could be improved a little by including the actual keys in the search (obviously single letters would be a problem).

The reason is that I was actually digging around in there before comming here, but never found the binding on my own because the search didn't respond to keywords like `space`, or `ctrl` 🤔.
