### ISSUE TITLE
Keyboard Navigation of SSH Selection UI

### ISSUE THREAD

**Issue by PratheekB** [Eugeny/terminus#1557]
I am able to open the SSH Selection UI with keyboard shortcut Alt+S. 
However, I am not able to navigate or search though the list of saved SSH connections.

Version: 1.0.91
Platform: win32 10.0.18362
Plugins: none

**Comment by xoner** [comment]
👍 

Same here, it's very frustrating to have to leave the keyboard and take the mouse in order to be able to select a previously saved ssh connection.

When <kbd>Alt</kbd> + <kbd>S</kbd> is pressed the focus moves to the Quick connect input, you should be able to filter existing ssh connections and move with the arrow keys between them to select the desired one
