### ISSUE TITLE
long line copy to clipboard work incorrectly

### ISSUE THREAD

**Issue by cheburx** [Eugeny/terminus#1558]
Version: 1.0.91
Platform: win32 10.0.17134
Plugins: none

When copy long line (actually in terminal window it looks like a lot of lines), terminal add carrage-returns at the end of screen.
It is very uncomfortable.

**Comment by bobbyiliev** [comment]
Yes, I've noticed the same problem here as well.

**Comment by kript** [comment]
Same for me on 1.092.  

This bug means that copying text isn't usable without trimming the line endings, which is often not possible when copy/pasting

**Comment by michal-serato** [comment]
Same issue. This is honestly a deal breaker for me and made me switch to other terminal apps. Very keen to have this fixed so that I can enjoy Terminus again.

**Comment by slhad** [comment]
Same for me on 1.0.106

It's causing a lot of problem when copy/paste logs, certs, base64 string

**Comment by Bboy4life** [comment]
Same

**Comment by Eugeny** [comment]
The issues with line wrapping on Windows are due to Windows processing line wrapping before output even gets to Terminus. I've just added some heuristics to try and "unroll" the wrapped lines where possible.

Also, enabling ConPTY (Settings -> Shell) should in theory prevent Windows from doing line wrapping.

**Comment by slhad** [comment]
Still doing it with 1.0.107 with and without ConPTY and with git-bash and cmd (stock)
