### ISSUE TITLE
Audible bell even when disabling it

### ISSUE THREAD

**Issue by haggaie** [Eugeny/terminus#169]
Hi,

I'm using Terminus alpha 16 on Windows with WSL, and when the terminal sounds a beep (e.g. in backspace on an empty line in bash) it makes a relatively long sound. This happens even though the "Terminal Bell" setting is set to Off.

Any other way to disable this sound?

**Comment by JostCrow** [comment]
Alpha 27 is out. Maybe you should upgrade. I have the visual feedback enabled an I do not hear the bell sound.

**Comment by haggaie** [comment]
Thanks, I'll try upgrading.

**Comment by haggaie** [comment]
I upgraded to alpha 27 (although in the settings/plugins form the terminus is shown as alpha 24 for some reason). Still the problem persists.

**Comment by ClementParis016** [comment]
There is actually no reliable way to disable the terminal bell in WSL and even if we would end up having one in the future, that would be a user preference to set on the bash profile or configuration itself, so I think it's out scope for Terminus to try to handle that for us.

**Comment by haggaie** [comment]
@ClementParis016 are you saying that WSL sounds the bell itself, without the terminal's involvement?

If that's the case I agree it's out of scope, and I should open a bug against WSL...

**Comment by ClementParis016** [comment]
@haggaie Yes sort of, you can check this if you open the "Bash on Ubuntu" system application you will hear that it also sounds the bell.

I've read that people usually mute the system command line from the volume icon in the system tray, which seems to be the most reliable way to do it. 

Though, that makes me wonder if muting the Terminus app from within itself would work, since [Electron has some API for this](https://electron.atom.io/docs/all/#contentssetaudiomutedmuted).

I wanted to try this but couldn't run a working clone of the repo on my computer, maybe @Eugeny could work on improving the setup to make contributing easier?

**Comment by Eugeny** [comment]
@ClementParis016 at what step of the [guide](https://github.com/Eugeny/terminus/blob/master/HACKING.md) are you?

**Comment by ClementParis016** [comment]
@Eugeny I had a bunch of issues at `./scripts/install-deps.js` that I couldn't fix, don't remember exactly what it was as I'm not on my personal computer at the moment, I will check that again and open a separated issue if needed.

**Comment by Eugeny** [comment]
@ClementParis016 would appreciate if you could share your getting-started experience - this might help future users

**Comment by ClementParis016** [comment]
@Eugeny yep, I've opened an issue at #221

**Comment by haggaie** [comment]
Thanks @ClementParis016, I followed the workarounds at https://github.com/Microsoft/BashOnWindows/issues/715 and https://stackoverflow.com/q/36724209/46192 and they seem to help.
