### ISSUE TITLE
History search like Cmder

### ISSUE THREAD

**Issue by NN---** [Eugeny/terminus#1882]
[Cmder](https://cmder.net/) stores command history and output and allows searching.
Terminus should be able to do it too.

**Comment by Eugeny** [comment]
History is provided by the shell, not the terminal. Almost every shell comes with history support today. 
The shell used in Cmder (clink) is embedded in Terminus as well.

**Comment by NN---** [comment]
It doesn't work the same way as cmder .
The history is not saved after I close and open a new tab

**Comment by lackovic** [comment]
It doesn't work for me either: when I open a new tab the `reverse-i-search` history is empty.

**Comment by AntonioRedondo** [comment]
Not sure if it's the same issue. But on Windows the history isn't filtered by the text already typed.

For example, on macOS, if in the terminal is written
```
npm
```
and I press the key `Up`, the history only will iterate over entries that start by `npm`:
```
npm i
npm list
npm view
```

However, on Windows using as shell Git-Bash or clink, what it's already written on the terminal will be ignored and when pressing `Up` history will iterate over all entries in reverse chronological order.
```
npm i
git status
ls -la
npm list
```

Is this behaviour caused because nor clink nor Git-Bash support filtering history?

**Comment by Eugeny** [comment]
@AntonioRedondo history autocompletion on windows is notoriously bad, but that's not in Terminus' scope - it's only hosting whatever shell you're running and the shell provides history/autocompletion.

**Comment by AntonioRedondo** [comment]
So after further investigation I discovered that history partial completion is actually available in several Windows shells:

### PowerShell
<kbd>F8</kbd>. Then <kbd>Enter</kbd> to select the history entry you want

### Clink
<kbd>Ctrl</kbd>+<kbd>PgUp</kbd>/<kbd>Ctrl</kbd>+<kbd>PgDown</kbd>.

### GitBash for Windows
<kbd>↑</kbd>/<kbd>↓</kbd> after adding the below entries to `C:\Program Files\Git\etc\inputrc`:

```
"\e[A": history-search-backward
"\e[B": history-search-forward

**Comment by daomengRen** [comment]
I don't know if anyone will make a plug-in for this feature, looking forward to it
