### ISSUE TITLE
Warn on Multiline Paste

### ISSUE THREAD

**Issue by Fizzixnerd** [Eugeny/terminus#2131]
**Type**
Enhancement/Feature Request

**What You Do**

1. Copy a multiline string from somewhere, such as: 
```text
hello
world
```
2. Paste this into the terminal window

**What You See**

The pasted text is entered without a warning and immediately executed by the shell.

**What You Expect**

A popup dialog confirming that you really wanted a multi-line paste.  In my experience, you usually don't.  

You would probably want a configuration option to enable/disable this for other people's sanity's sake.

**Other Notes**

This is different from the existing bracketed paste, because it (hopefully?) wouldn't require shell integration to work.

I think I've found the location where you would implement this? https://github.com/Eugeny/terminus/blob/ceb75323fefa788d0cb7032df3d4cf0aee258722/terminus-terminal/src/api/baseTerminalTab.component.ts#L273.  You would add a check here to see if "multiline pasting warning" was enabled, and if so, check the `data` variable for newlines and warn accordingly.

**Comment by LoSz** [comment]
is it possible to somehow deactivate this warning?

**Comment by Eugeny** [comment]
In the nightly build it can be disabled from the settings

**Comment by LoSz** [comment]
@Eugeny 
awesome thank you!!

**Comment by diegosomar** [comment]
Now, we have the option `multiLinePasteWarning` which can be defined as `false`.

**Comment by Muhimen123** [comment]
Thank's it worked for me now.

**Comment by alowde** [comment]
Could I humbly request that changes to user experience like this default to disabled, rather than changing default behaviour? Alternatively could/should the setting for disabling the warning be documented in the warning message?

Searching for 'windows terminal newline warning' brought up a number of irrelevant results unfortunately, and I couldn't find it in the documentation. Thanks @diegosomar for mentioning the setting.

**Comment by durera** [comment]
> Could I humbly request that changes to user experience like this default to disabled, rather than changing default behaviour?

Or at minimum, document these changes somewhere in a "what's changed" with details on how to restore previous behavior after the update; came across this issue trying to work out how to get rid of a couple of new warnings that had been bugging me today. It turned out to be easy to do [once you know what needs to be done](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#paste-warnings), but difficult to find out what needed to be done in the first place until I had the name of the setting to search through the docs for from the comment above.

**Comment by mboeker** [comment]
Even with "multiLinePasteWarning: false" windows is asking me every time. This did work a month or two ago, but now it isn't anymore... Any suggestions?

**Comment by mboeker** [comment]
Found that in the nightly build when you turn off the warning, in the config file it goes under:
```
terminal:
  warnOnMultilinePaste: false
```

**Comment by ShravanSunder** [comment]
multiLinePasteWarning doesn't seem to work for me still
