### ISSUE TITLE
SSH plugin does not respect keys loaded into SSH-Agent

### ISSUE THREAD

**Issue by viertaxa** [Eugeny/terminus#2184]
When a key is added to the local SSH Agent via ssh-add, Terminus still prompts you for the credentials for the default SSH key, despite that key being present and unlocked in the agent.

**Comment by damccull** [comment]
This is the biggest thing I need too. I currently use xterm and, while, on occasion I use its built in ssh tunneling, I'd like to have a more modern and nice looking UI. I very much like terminus, but I need it to respect the ssh agent because I use a smart card for my ssh keys. The agent handles authentication of the card and passes on the appropriate data to the calling program.

**Comment by Eugeny** [comment]
Please include your OS and which SSH agent you're using.
