### ISSUE TITLE
Windows install gets stuck / fails with error 5 (user cancelled action)

### ISSUE THREAD

**Issue by aibars** [Eugeny/terminus#2256]
While trying to install 1.0.104 on Windows I get the following error:

```
ERROR: Running ["C:\Users\%user%\AppData\Local\Temp\chocolatey\terminus\1.0.104\terminus-1.0.104-setup.exe" /S ] was not successful. Exit code was '5'. Exit code indicates the following: User (you) cancelled the installation..
The install of terminus was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\terminus\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by mictaege** [comment]
I came across this case while searching the Internet, because I run into the same problem after accidentally canceled a previous terminus installation.

Now I get this error message every time I try to reinstall terminus on my machine and I can't figure out how to make a new installation work, e.g. by removing certain remnants of the canceled installation or something similar.

Any hints?
