### ISSUE TITLE
Open more 4 tab will hang Terminus

### ISSUE THREAD

**Issue by PePoDev** [Eugeny/terminus#3337]
>Version: 1.0.126
>Platform: win32 10.0.19042
>WSL

When open 5th tab, Terminus will hang !
After I press `CTRL+Shitf+t` to open tab serveral time, Terminus will hang in 5th tab.
I try to close some tab with `Ctrl+d`, Then all tab that I open in previous time will open !!.

**Comment by EduardoSantanaSeverino** [comment]
Hi PePoDev, 

it is not happening for me. 

I am using the windows 10 installed version.

**Comment by schoenj** [comment]
Hi,
i have the same issue on Ubuntu 20.04 with the latest release (v1.0.127).

When i open up devTools, it prints everytime i open a new tab (only till the 4th tab) the following error.
GET file://opt/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND

Because PePoDev uses WSL (so a linux subsymstem, right?), is it possible that this issue only happens on linux?
And @PePoDev: Do you get the same error shown in devtools?

**Comment by PePoDev** [comment]
@schoenj How to open devTools ? 🤣

**Comment by PePoDev** [comment]
Oh I found it
>/C:/Program%20Files/Terminus/resources/app.asar/dist/[object%20Module]:1 GET file:///C:/Program%20Files/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND

**Comment by combin** [comment]
If faced this issue too start from v1.0.124. v1.0.123 woks OK for me.
> Edition	Windows 10 Pro
> Version	20H2
> Installed on	‎5/‎29/‎2020
> OS build	19042.746
> Experience	Windows Feature Experience Pack 120.2212.551.0
> WSL 2

**Comment by rogerfc** [comment]
Facing the same issue on v1.0.126

> Version: 1.0.126
> Platform: win32 10.0.19042
> Plugins: altair, relaxed-theme, title-control
> WSL 2 with Ubuntu 20.04

The 5th+ tab opens after 1 minute or so, but it is extremely annoying.

**Comment by Eugeny** [comment]
Fixed in v130
