### ISSUE TITLE
Can't Install Ubuntu 18.04

### ISSUE THREAD

**Issue by SC7639** [Eugeny/terminus#339]
When trying to install on Ubuntu 18.04 the ubuntu software asks for my password which I enter and then it goes to 100% install but then the screen refreshes and the install button is back and I can't open terminus. See the photo's below.

![screenshot from 2018-05-07 17-05-04](https://user-images.githubusercontent.com/6049560/39711997-646e0708-5219-11e8-85eb-0319133d8d35.png)

![screenshot from 2018-05-07 17-09-36](https://user-images.githubusercontent.com/6049560/39712017-718db6ea-5219-11e8-9ed4-9ff14a5f1d26.png)

**Comment by TacoGS** [comment]
I am running into the same issue with Ubuntu 18.04 and installing Terminus. The problem seems to be they removed a dependency from the standard repositories and it is complaining about `python-gnomekeyring` and won't install without it. 

 https://launchpad.net/ubuntu/+source/gnome-python-desktop/+publishinghistory

From what I can tell it was removed intentionally as the dependencies are broken.

Trying to work on a solution but in order to do that it would take a massive effort to restore gnome python desktop.

**Comment by radicaldrew** [comment]
I was able to install terminus on my ubuntu 18.04 
I found the package for python-gnomekeyring and installed it myself.

wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gnome-python-desktop/python-gnomekeyring_2.32.0+dfsg-3_amd64.deb
sudo dpkg -i python-gnomekeyring_2.32.0+dfsg-3_amd64.deb

I was missing a few dependencies
sudo apt-get install libutempter0 screen tmux
