### ISSUE TITLE
[Plain text password] I need to enable plain text password in Terminus

### ISSUE THREAD

**Issue by starxg** [Eugeny/terminus#3670]
I have developed a plugin([terminus-sync-config](https://github.com/starxg/terminus-sync-config)), but it cannot synchronize passwords.

I found that the password of ssh is encrypted by keytar.

Can you add a way to save in plaintext format?  Although this is not safe, you can choose to use keytar by default.

My English is not very good, I hope you can understand what I mean. Thank you. 🌹

<img width="484" alt="like this" src="https://user-images.githubusercontent.com/34997494/113590376-24e85000-9665-11eb-8735-e2be164b4b9b.png">

**Comment by Eugeny** [comment]
Hi, first of all - a very cool plugin!

You can use `keytar` directly from your plugin to read plaintext passwords from the user's keychain. You don't need to include `keytar` into your plugin's `dependencies` since it's already bundled with Terminus (just add it to Webpack's `externals` so that the Terminus' version is used).

Check out how passwords are loaded in the SSH plugin itself: https://github.com/Eugeny/terminus/blob/bd46b08c9d909603eca4f1ca149d9a2d0155117f/terminus-ssh/src/services/passwordStorage.service.ts#L28

**Comment by Eugeny** [comment]
Hi, first of all - a very cool plugin!

You can use `keytar` directly from your plugin to read plaintext passwords from the user's keychain. You don't need to include `keytar` into your plugin's `dependencies` since it's already bundled with Terminus (just add it to Webpack's `externals` so that the Terminus' version is used).

Check out how passwords are loaded in the SSH plugin itself: https://github.com/Eugeny/terminus/blob/bd46b08c9d909603eca4f1ca149d9a2d0155117f/terminus-ssh/src/services/passwordStorage.service.ts#L24-L28

**Comment by Eugeny** [comment]
@allcontributors please add @starxg for plugins

**Comment by starxg** [comment]
wow, This seems to be a good idea. thank you.
