### ISSUE TITLE
There is package on ubuntu store named terminus which is conflicting with installation of dep file

### ISSUE THREAD

**Issue by ziarv** [Eugeny/terminus#3741]
Selecting previously unselected package terminus.
(Reading database ... 212026 files and directories currently installed.)
Preparing to unpack terminus-1.0.137-linux.deb ...
Unpacking terminus (1.0.137) ...
dpkg: dependency problems prevent configuration of terminus:
 terminus depends on gconf2; however:
  Package gconf2 is not installed.
 terminus depends on gconf-service; however:
  Package gconf-service is not installed.
 terminus depends on libappindicator1; however:
  Package libappindicator1 is not installed.

dpkg: error processing package terminus (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 terminus

**Comment by amajauskas** [comment]
That does not seem to be the case though, its failing because of missing dependencies as listed in your output:

> dpkg: **dependency** problems prevent configuration of terminus:
terminus depends on gconf2; however:
_**Package gconf2 is not installed.**_
terminus depends on gconf-service; however:
_**Package gconf-service is not installed.**_
terminus depends on libappindicator1; however:
_**Package libappindicator1 is not installed.**_

**Comment by larp-welt** [comment]
Same probleme here. Terminus gets deinstalled at each update. And this package is installed instead:

![2021-05-19_23-46](https://user-images.githubusercontent.com/392672/118889026-c7e6e780-b8fc-11eb-8189-e6c42ea4bd3e.png)
