### ISSUE TITLE
Plugin issue upon launch of 1.0.140

### ISSUE THREAD

**Issue by cjerrington** [Eugeny/terminus#4013]
Updated to the latest version today and got the following error. The only plugin I think it could be related to is the Clickable Links plugin. 

![image](https://user-images.githubusercontent.com/8809376/122688394-999d4600-d1e1-11eb-8fa7-fa3ab065dbd9.png)

Version: 1.0.140
Platform: win32 10.0.19041
Plugins: none

**Comment by linqinghuang** [comment]
same problem on macos big sur 11.4

**Comment by Tyr4El** [comment]
me too, on ubuntu/fedora/windows 10 pro

**Comment by starxg** [comment]
hi, @Eugeny 

It may be caused by the removal of ElectronService from terminus-core. Is that so?


![1D13F34B-4ADA-484E-9D12-0C1271A1572E](https://user-images.githubusercontent.com/34997494/122701440-d6b81580-d27f-11eb-9e01-636a426148be.png)


### clickable-ips plugin
[https://github.com/GG4mida/terminus-clickable-ips/blob/8787116ae9cdb2a2f0147094877174f10f295ae5/src/handlers.ts#L6](https://github.com/GG4mida/terminus-clickable-ips/blob/8787116ae9cdb2a2f0147094877174f10f295ae5/src/handlers.ts#L6)
```JavaScript
import { ElectronService } from 'terminus-core'
constructor (
    protected toastr: ToastrService,
    protected electron: ElectronService,
) {
    super()
}
```


### sync-config plugin
[https://github.com/starxg/terminus-sync-config/blob/1.0.5/src/components/SettingsTab.component.ts#L2](https://github.com/starxg/terminus-sync-config/blob/1.0.5/src/components/SettingsTab.component.ts#L2)
```JavaScript
import { ConfigService, ElectronService, } from 'terminus-core'
 constructor(
    public config: ConfigService,
    private toastr: ToastrService,
    private electron: ElectronService,
    private passwordStorage: PasswordStorageService
) {}
```

**Comment by Eugeny** [comment]
✅  Clickable links: v3.0.0

**Comment by Eugeny** [comment]
☑️ Clickable IPs: PR submitted https://github.com/GG4mida/terminus-clickable-ips/pull/1

**Comment by Eugeny** [comment]
☑️ Sync config: PR submitted https://github.com/starxg/terminus-sync-config/pull/12

**Comment by Mozart409** [comment]
@Eugeny how can I manually uninstall those plugins? My terminus installation always starts in savemode?

**Comment by Eugeny** [comment]
@Mozart409 you have to remove them from the plugin folder manually - click Settings -> Plugins -> Plugins folder

**Comment by Mozart409** [comment]
> @Mozart409 you have to remove them from the plugin folder manually - click Settings -> Plugins -> Plugins folder

It worked. Thank you

**Comment by cjerrington** [comment]
Looks like manually removing the plug for terminus-clickable-links then reinstalling the 3.0.1 version worked. Thanks @Eugeny and everyone else.
