### ISSUE TITLE
Hotkeys dont work properly

### ISSUE THREAD

**Issue by LuisRocamonde** [Eugeny/terminus#446]
Version: 1.0.0-alpha.58
Platform: win64 10.0.16299
Plugins: 

The hotkeys dont work properly, close and open tab fail if u have a hotkey like Ctrl-T. 
If u use like hotkey Ctrl-Alt-T it works fine.

**Comment by webmin88** [comment]
I'd like to report and expand on this issue as well:

Version: 1.0.0-alpha.62
Platform: win32 10.0.17134
Plugins: altair, clickable-links, quick-cmds, scrollbar, shell-selector, theme-gruvbox, theme-hype, theme-windows10, title-control

Mine is specifically around Ctrl + Backspace, Ctrl + Del, Ctrl + Left Arrow, Ctrl + Right Arrow. Instead of the expected action, Ctrl + Backspace as an example inserts ^H in my terminal. I've only experienced this behavior in PowerShell so far; I have not had a chance to test in other shells.

Please let me know if I can contribute any additional information to help troubleshoot this issue.

**Comment by Eugeny** [comment]
@webmin88 your issue is #507

**Comment by Peter-Optiway** [comment]
I'm having the same issue, ctrl + arrow does nothing but works correctly in the normal powershell terminal.
