### ISSUE TITLE
Vibrancy no longer work on windows

### ISSUE THREAD

**Issue by Vardiak** [Eugeny/terminus#460]
I just updated to alpha 59 and vibrancy no longer work :(

Version: 1.0.0-alpha.59
Platform: win32 10.0.17134
Plugins:

**Comment by mikemaccana** [comment]
FWIW, I'm using alpha 59 on 10.0.17763.0 and it works.

**Comment by Eugeny** [comment]
@hummal could you please capture a Performance trace from the DevTools?

**Comment by hummal** [comment]
First of all the vibrancy proof:
![terminus_vibrancy](https://user-images.githubusercontent.com/633711/46863672-4c555d80-ce18-11e8-980e-926ebd51096a.gif)




Second trace:
[terminus_profile.json.txt](https://github.com/Eugeny/terminus/files/2472646/terminus_profile.json.txt)

1. Open settings tab
2. change customcss 
3. repeat

**Comment by Eugeny** [comment]
@hummal thanks for the trace. Could you please check if this build https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts helps with the CPU usage?

**Comment by hummal** [comment]
Seems to be the same. Trace profile attached.

Workflow:

1. open settings tab
2. start trace
3. change customcss
4. change customcss
5. stop trace
[Profile-20181012T135125.json.txt](https://github.com/Eugeny/terminus/files/2472910/Profile-20181012T135125.json.txt)

**Comment by sylveon** [comment]
As I've noted before, broken vibrancy is due to a bug in DWM's implementation of this blur, only under certain conditions does it not crap itself. It's also possible that it's the cause of the high CPU usage.

It's why I suggested to use the old less fancy but stable blur as default and maybe making the new but buggy blur as option somewhere. A dropdown would be the best IMO on Windows as the API supports 3 states: transparent only - ACCENT_ENABLE_TRANSPARENTGRADIENT, blur - ACCENT_ENABLE_BLURBEHIND (not buggy) and fluent - ACCENT_ENABLE_FLUENT (the buggy one). On Windows 7 & 8 only "blur" would be available, via windows-blurbehind.

**Comment by sylveon** [comment]
I may try to find some time for implementing such a thing this weekend

**Comment by Eugeny** [comment]
@sylveon thanks - I'm already in progress of adding a separate option to select the accent type - coming soon
