### ISSUE TITLE
Некоторые пожелания \ вопросы

### ISSUE THREAD

**Issue by oxionex** [Eugeny/terminus#523]
Привет. Хочу вначале поблагодарить за работу в данной области - действительно, если этот проект продолжит развиваться, он выльется в нечто действительно крутое для Windows. Но есть некоторые пожелания, которые, мой взгляд, могут улучшить проект:

1)Поскольку работаю с сетевым оборудованием, мне требуется биндить скрипты на логин. Сначала идет коннект по ssh на рабочий сервер, а затем уже с него по telnet \ ssh идет коннект на оборудование. Там и нужны бинды, чтобы не вводить вручную логин \ пароль. Не совсем понял, как рамках твоего продукта можно реализовать данную возможность. Если есть возможность на данном этапе это реализовать - подскажи, пожалуйста. Буду премного благодарен

2)Не всегда работает клавиша Backspace. Допустим, если напрямик заходить на оборудование - работает. Если сначала на специальный сервер, а затем уже на оборудование - не работает. В рамках других клиентов это решалось выбором в настройках Control + H. Пример такового функционала в KiTTY - http://prntscr.com/llaxok

3)Ограничение на кол-во строк. В рамках других клиентов можно выбрать то кол-во строк, которое будет хранить в себе клиент. Хотелось бы увидеть это и в твоем продукте.

Заранее спасибо

UPD: Первый и второй пункт костылятся легко черз AutoHotKey:

#IfWinActive ahk_exe Terminus.exe
BACKSPACE::Send, ^{H}
!W::Send, password{Enter}
!Q::Send, login{Enter}password{Enter}
#IfWinActive

Но хотелось бы нативного решения

**Comment by khashashin** [comment]
Translation:
Hey. I want to thank first for the work in this area - indeed, if this project continues to evolve, it will turn into something really cool for Windows. But there are some wishes that, in my opinion, can improve the project:

1) Since I work with network equipment, I need to bind scripts to login. At first, there is a connection via ssh to the working server, and then from it via telnet \ ssh there is a connection to the equipment. There are needed binds, so as not to manually enter the username/password. I didn’t quite understand how within your product you can realize this opportunity. If there is an opportunity at this stage to implement it - tell me, please. I would be very grateful

2) The Backspace key does not always work. For example, if you go straight to the equipment, it works. If you first on a special server, and then on equipment, it does not work. Within other clients, this was decided by choosing Control + H in the settings. An example of such functionality in KiTTY is http://prntscr.com/llaxok

3) Limit the number of lines. As part of other clients, you can choose the number of lines that the client will keep. I would like to see it in your product.

Thank you in advance
