### ISSUE TITLE
Support changing color scheme from within a shell (Base16 etc)

### ISSUE THREAD

**Issue by tnguyen14** [Eugeny/terminus#59]
It'd be great for terminus to add 256 colors support. Right now, when I run this test https://github.com/chriskempson/base16-shell/blob/master/colortest, colors 17-21 are shown as blue (https://github.com/chriskempson/base16-shell#troubleshooting)

**Comment by Eugeny** [comment]
Terminus _does_ support 256 colors as per https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263

You see the blue colors because Terminus doesn't support changing color scheme from within a shell - and the blue hues are the default values for colors 16-21 from the 256-color space. 
I'll rename this ticket.
