### ISSUE TITLE
Text Boldness

### ISSUE THREAD

**Issue by ninuola** [Eugeny/terminus#656]
Please is there a way to make the text in the terminal regular instead of bold?

**Comment by Eugeny** [comment]
This fully depends on the font you've selected in the Appearance settings page.

**Comment by ninuola** [comment]
Thanks for the quick response. Do you know which fonts display regular-type texts by default?

**Comment by Eugeny** [comment]
Normally, all of them. Which font are you currently using? A screenshot would be helpful too.

**Comment by ninuola** [comment]
I'm using Consolas at the moment.

**Comment by ninuola** [comment]
I have tried other ones by the way, and they all appear to be bolder than how they look on Kitty, OneNote, and Word.

**Comment by ninuola** [comment]
![terminus_2](https://user-images.githubusercontent.com/1965655/52567836-2317fe80-2e05-11e9-972f-b1fd6b9eb205.PNG)

Is it just me or does the text at the bottom look bolder than the one at the top? Thanks for your time.

**Comment by ninuola** [comment]
Maybe not bolder actually but the text at the top looks sharper, right?

**Comment by Eugeny** [comment]
Thanks. You could try switching between the two terminal frontends - they use different font rendering (`hterm` - normal Chrome, `xterm` - canvas based).

**Comment by ninuola** [comment]
That helped. Thanks for your time man.

**Comment by renraw** [comment]
I have same issue but hterm is not a option anymore

**Comment by georgitrifonov** [comment]
I also have the same problem

**Comment by lynara** [comment]
same here, any possibility to change this?

**Comment by readonly24** [comment]
Any update on this? In comparison my Putty screen is much more readable without bold letters.

**Comment by georgitrifonov** [comment]
> Any update on this? In comparison my Putty screen is much more readable without bold letters.

The two terminals don't share a rendering stack, so this isn't really a settings mismatch — it's Core Text vs. Chromium.

Why it happens

iTerm2 draws glyphs with Core Text and, on Retina displays, defaults to thinner strokes for anti-aliased text when the background is darker than the foreground. [iTerm2](https://iterm2.com/documentation-preferences-profiles-text.html)
 Tabby is Electron + xterm.js, so it goes through Chromium, which gets macOS's "font dilation" — the OS artificially inflates glyph outlines, effectively bolding them. [Skip](https://skip.house/blog/macos-font-rendering)
 Same font, same size, visibly heavier.

Fix 1 — disable font smoothing for Tabby only (biggest single win)

Tabby's bundle ID is org.tabby, so you can scope this to just that app instead of the whole system:

`defaults write org.tabby AppleFontSmoothing -int 0`
