### ISSUE TITLE
Non-ASCII text issue

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#789]
OS: Windows 10

![Honeycam 2019-04-29 19-40-41](https://user-images.githubusercontent.com/46282492/56891415-4e7ec100-6ab7-11e9-9b03-e70d1bae41dc.gif)
![Honeycam 2019-04-29 19-47-03](https://user-images.githubusercontent.com/46282492/56891494-99003d80-6ab7-11e9-8e03-a191ed71169c.gif)

In `hterm` mode, If I type non-ASCII(Korean) text in the terminal, it appears bottom or top of the screen and doesn't disappear.

![Honeycam 2019-04-29 19-55-37](https://user-images.githubusercontent.com/46282492/56891860-d1544b80-6ab8-11e9-8684-771855ea84f2.gif)

In `xterm` mode, there is no issue like above but non-ASCII text is displayed with black color, so it is hard to distinguish.

I think `xterm` mode is better, except #755 and this text color problem. Please allow to change color of non-ASCII words.

**Comment by Alex4386** [comment]
xterm issue is likely because of `3.13.0-beta1`'s issue.  
try creating issue at the [xterm.js](https://github.com/xtermjs/xterm.js).

build results of master branch (xterm == 3.13.0-beta1)
![image](https://user-images.githubusercontent.com/27724108/56912454-3ffdcd00-6aea-11e9-8419-71c5aa98696c.png)  
  
build results of modified version of master branch  
(xterm version of terminus-terminal was modified to 3.12.2)  
![image](https://user-images.githubusercontent.com/27724108/56912600-8d7a3a00-6aea-11e9-895b-2f98eb4a059d.png)

**Comment by NDelt** [comment]
@Alex4386 How can I modify xterm version of Terminus?

**Comment by Eugeny** [comment]
@NDelt you can't do it on a normal install - I'll release an update with a rolled back xterm version today

**Comment by Eugeny** [comment]
Ref https://github.com/xtermjs/xterm.js/issues/2031

**Comment by Eugeny** [comment]
Fixed in xterm
