### ISSUE TITLE
Add ssh port forward

### ISSUE THREAD

**Issue by lucawen** [Eugeny/terminus#821]
A port forward manager for every ssh connection will be a good feature!!

**Comment by pquerner** [comment]
Thats what the ssh config is for, or am I missing something?

**Comment by lucawen** [comment]
> Thats what the ssh config is for, or am I missing something?

Yes... but with a manager, we can setup the configs more easy for specific connections... If you think like that, so why ssh manager exists?

**Comment by pquerner** [comment]
Ok, I see. So like PuTTy in a way. True, I can see that happening. I havent touched it in years since I learned how to use ~/.ssh/config but I can see its usefulness.

**Comment by lucawen** [comment]
I use the everything manual too.. but its some simple features thats i think will be nice to see in terminus.. 

I would implement it, as well as another feature that had already opened an issue here in the project, however my environment is not running very well the application :sob:, if it would not implement some things in the project :smile:

**Comment by massung** [comment]
Just noting that .ssh/config doesn't exist on Windows (or, if it exists somewhere, I don't know where), so configuration options in Terminus that pass the correct settings on the command line would be very valuable. I would also add SSH tunneling to the list as well, but that might be another feature request.

**Comment by surojmaharjan** [comment]
Is SSH tunneling in to do list?

**Comment by hdkiller** [comment]
Any workaround to enable this on the windows client?

**Comment by massung** [comment]
Port forwarding works for me on the latest windows client fine. 

This took me way too long to figure out (and I emailed them about making the UI more obvious), but if you're coming from Putty, the issue is that port forwarding is orthogonal to opening a terminal connection to the host. 

With putty you setup port forwarding _as part of the host connection_ so that while connected the port is forwarded.

With Termius, however, you make a port forwarding rule, _which you connect independently of a shell_. You need to right-click the rule and select "Connect". The icon next to the rule should turn from gray (disconnected) to blue (connected). 

Does this help?

**Comment by hdkiller** [comment]
Hello!

Unfortunately I don't use Putty, so I don't know how it's works there. (I use Terminator in a Debian VM on Windows, for ssh..) I don't find on the Terminus UI how to make a port forwarding rule, could you please give me more directions please? :) 

I was browsing the source and I found out that node ssh2 supports port forwarding, so it would be trivial to implement this in the terminus-ssh module and put some input fields to the Advanced tab of a connection which mimics ssh -s syntax.

Thanks!

**Comment by ahbrajev** [comment]
What's up with this issue?!

**Comment by pgeeh** [comment]
> What's up with this issue?!

It seems to have been added in the closed merge, but I cannot seem to find out how to get the modal to appear.
