### ISSUE TITLE
There are two problems when I using it

### ISSUE THREAD

**Issue by yelijun** [Eugeny/terminus#833]
Version: 1.0.77
Platform: darwin 18.0.0
Plugins: none

1. Multi tabs, switch and open a new tab the '+' button does now work some times.
2. After switch back the terminal, the prefix will disappear, after typing any char, it show back again, if does not type anything, it will keep the blink

**Comment by ZaLiTHkA** [comment]
I noticed this same behaviour on Windows while using `xterm` as the "Frontend", switching this over to `hterm` instead seems to sort it out. maybe try that and see if it helps in the meantime?

the Windows side of this issue was reported in #755, not sure if it's the same problem affecting all platforms though.

**Comment by Eugeny** [comment]
1. Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

2. Duplicate of #729

**Comment by whyboris** [comment]
1. Clicking on the `+` the first time outlines the button and a new tab is created only on the second press of the `+` 😖 The behavior is not consistent -- I am able to replicate every time when starting the app. Same problem happens when clicking the settings (gear) icon (it outlines on first click, opens on second).

I'm on _Mac OS X_ `10.13.6` and _Terminus_ `1.0.85.1844` (appearance `xterm (WebGL)`)
