### ISSUE TITLE
ctrl+D kills the terminal but does not close the tab

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#84]
![terminus-ps](https://user-images.githubusercontent.com/1329716/27890922-70f00542-6239-11e7-809d-8772d7279c7b.gif)

After pressing ctrl+d, typing is no longer making a difference, but the tab is still there. It should really be closed after that. I could just bind ctrl+d to close tab, but that will make life hard when using REPLs, e.g. node.

**Comment by enriquein** [comment]
I'm not sure if I should open a new issue, but if you are using a command that expects you to use CTRL+D to end input (for example, when using `at -t`) then this will abruptly close the tab instead of letting `at` handle the CTRL+D input. I have to switch to an alternate terminal app whenever I need to do anything involving CTRL+D. Could this behavior perhaps be optional?
